trigger: none
pool: pipele_new

stages:
  - stage: init
    jobs:
      - job: init
        steps:
        - task: TerraformInstaller@1
          inputs:
            terraformVersion: 'latest'

        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'init'
            workingDirectory: '$(System.DefaultWorkingDirectory)/Environment/Dev'
            backendServiceArm: 'manoj bhai sp'
            backendAzureRmResourceGroupName: 'rgs'
            backendAzureRmStorageAccountName: 'stg'
            backendAzureRmContainerName: 'ggggdd'
            backendAzureRmKey: 'saurabh.tfstate'


