trigger: none
pool: pipele_new

stages:
  - stage: terraforminstall
    jobs:
      - job: init
        steps:
        - task: TerraformInstaller@1
          inputs:
            terraformVersion: 'latest'
  - stage: terraforminit
    jobs:
      - job: init
        steps:
        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'init'
            workingDirectory: '$(System.DefaultWorkingDirectory)/Environment/Dev'

  - stage: plan
    jobs:
      - job: plan
        steps:
        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'plan'
            workingDirectory: '$(System.DefaultWorkingDirectory)/Environment/Dev'